{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting datetime\n",
      "  Downloading DateTime-5.0-py3-none-any.whl (52 kB)\n",
      "     --------------------------------------- 52.1/52.1 kB 41.2 kB/s eta 0:00:00\n",
      "Collecting zope.interface\n",
      "  Downloading zope.interface-5.5.2-cp310-cp310-win_amd64.whl (211 kB)\n",
      "     -------------------------------------- 211.7/211.7 kB 2.1 MB/s eta 0:00:00\n",
      "Requirement already satisfied: pytz in c:\\python310\\lib\\site-packages (from datetime) (2022.7)\n",
      "Requirement already satisfied: setuptools in c:\\python310\\lib\\site-packages (from zope.interface->datetime) (63.2.0)\n",
      "Installing collected packages: zope.interface, datetime\n",
      "Successfully installed datetime-5.0 zope.interface-5.5.2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ip (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ip (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ip (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ip (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ip (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ip (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ip (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ip (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\python310\\lib\\site-packages)\n",
      "\n",
      "[notice] A new release of pip available: 22.3.1 -> 23.0.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting instaloader\n",
      "  Downloading instaloader-4.9.6.tar.gz (60 kB)\n",
      "     --------------------------------------- 60.5/60.5 kB 45.3 kB/s eta 0:00:00\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Requirement already satisfied: requests>=2.4 in c:\\python310\\lib\\site-packages (from instaloader) (2.28.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\python310\\lib\\site-packages (from requests>=2.4->instaloader) (2022.12.7)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\\python310\\lib\\site-packages (from requests>=2.4->instaloader) (1.26.13)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\python310\\lib\\site-packages (from requests>=2.4->instaloader) (2.1.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\python310\\lib\\site-packages (from requests>=2.4->instaloader) (3.4)\n",
      "Installing collected packages: instaloader\n",
      "  Running setup.py install for instaloader: started\n",
      "  Running setup.py install for instaloader: finished with status 'error'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ip (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ip (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ip (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\python310\\lib\\site-packages)\n",
      "  DEPRECATION: instaloader is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559\n",
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  × Running setup.py install for instaloader did not run successfully.\n",
      "  │ exit code: 1\n",
      "  ╰─> [54 lines of output]\n",
      "      running install\n",
      "      C:\\Python310\\lib\\site-packages\\setuptools\\command\\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.\n",
      "        warnings.warn(\n",
      "      running build\n",
      "      running build_py\n",
      "      creating build\n",
      "      creating build\\lib\n",
      "      creating build\\lib\\instaloader\n",
      "      copying instaloader\\exceptions.py -> build\\lib\\instaloader\n",
      "      copying instaloader\\instaloader.py -> build\\lib\\instaloader\n",
      "      copying instaloader\\instaloadercontext.py -> build\\lib\\instaloader\n",
      "      copying instaloader\\lateststamps.py -> build\\lib\\instaloader\n",
      "      copying instaloader\\nodeiterator.py -> build\\lib\\instaloader\n",
      "      copying instaloader\\sectioniterator.py -> build\\lib\\instaloader\n",
      "      copying instaloader\\structures.py -> build\\lib\\instaloader\n",
      "      copying instaloader\\__init__.py -> build\\lib\\instaloader\n",
      "      copying instaloader\\__main__.py -> build\\lib\\instaloader\n",
      "      copying instaloader\\py.typed -> build\\lib\\instaloader\n",
      "      running install_lib\n",
      "      creating C:\\Python310\\Lib\\site-packages\\instaloader\n",
      "      copying build\\lib\\instaloader\\exceptions.py -> C:\\Python310\\Lib\\site-packages\\instaloader\n",
      "      copying build\\lib\\instaloader\\instaloader.py -> C:\\Python310\\Lib\\site-packages\\instaloader\n",
      "      copying build\\lib\\instaloader\\instaloadercontext.py -> C:\\Python310\\Lib\\site-packages\\instaloader\n",
      "      copying build\\lib\\instaloader\\lateststamps.py -> C:\\Python310\\Lib\\site-packages\\instaloader\n",
      "      copying build\\lib\\instaloader\\nodeiterator.py -> C:\\Python310\\Lib\\site-packages\\instaloader\n",
      "      copying build\\lib\\instaloader\\py.typed -> C:\\Python310\\Lib\\site-packages\\instaloader\n",
      "      copying build\\lib\\instaloader\\sectioniterator.py -> C:\\Python310\\Lib\\site-packages\\instaloader\n",
      "      copying build\\lib\\instaloader\\structures.py -> C:\\Python310\\Lib\\site-packages\\instaloader\n",
      "      copying build\\lib\\instaloader\\__init__.py -> C:\\Python310\\Lib\\site-packages\\instaloader\n",
      "      copying build\\lib\\instaloader\\__main__.py -> C:\\Python310\\Lib\\site-packages\\instaloader\n",
      "      byte-compiling C:\\Python310\\Lib\\site-packages\\instaloader\\exceptions.py to exceptions.cpython-310.pyc\n",
      "      byte-compiling C:\\Python310\\Lib\\site-packages\\instaloader\\instaloader.py to instaloader.cpython-310.pyc\n",
      "      byte-compiling C:\\Python310\\Lib\\site-packages\\instaloader\\instaloadercontext.py to instaloadercontext.cpython-310.pyc\n",
      "      byte-compiling C:\\Python310\\Lib\\site-packages\\instaloader\\lateststamps.py to lateststamps.cpython-310.pyc\n",
      "      byte-compiling C:\\Python310\\Lib\\site-packages\\instaloader\\nodeiterator.py to nodeiterator.cpython-310.pyc\n",
      "      byte-compiling C:\\Python310\\Lib\\site-packages\\instaloader\\sectioniterator.py to sectioniterator.cpython-310.pyc\n",
      "      byte-compiling C:\\Python310\\Lib\\site-packages\\instaloader\\structures.py to structures.cpython-310.pyc\n",
      "      byte-compiling C:\\Python310\\Lib\\site-packages\\instaloader\\__init__.py to __init__.cpython-310.pyc\n",
      "      byte-compiling C:\\Python310\\Lib\\site-packages\\instaloader\\__main__.py to __main__.cpython-310.pyc\n",
      "      running install_egg_info\n",
      "      running egg_info\n",
      "      writing instaloader.egg-info\\PKG-INFO\n",
      "      writing dependency_links to instaloader.egg-info\\dependency_links.txt\n",
      "      writing entry points to instaloader.egg-info\\entry_points.txt\n",
      "      writing requirements to instaloader.egg-info\\requires.txt\n",
      "      writing top-level names to instaloader.egg-info\\top_level.txt\n",
      "      reading manifest file 'instaloader.egg-info\\SOURCES.txt'\n",
      "      adding license file 'LICENSE'\n",
      "      adding license file 'AUTHORS.md'\n",
      "      writing manifest file 'instaloader.egg-info\\SOURCES.txt'\n",
      "      Copying instaloader.egg-info to C:\\Python310\\Lib\\site-packages\\instaloader-4.9.6-py3.10.egg-info\n",
      "      running install_scripts\n",
      "      Installing instaloader-script.py script to C:\\Python310\\Scripts\n",
      "      error: [Errno 13] Permission denied: 'C:\\\\Python310\\\\Scripts\\\\instaloader-script.py'\n",
      "      [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "error: legacy-install-failure\n",
      "\n",
      "× Encountered error while trying to install package.\n",
      "╰─> instaloader\n",
      "\n",
      "note: This is an issue with the package mentioned above, not pip.\n",
      "hint: See above for output from the failure.\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ip (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ip (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -p (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ip (c:\\python310\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\python310\\lib\\site-packages)\n",
      "\n",
      "[notice] A new release of pip available: 22.3.1 -> 23.0.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "!pip install datetime\n",
    "!pip install instaloader"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "ename": "BadCredentialsException",
     "evalue": "Login error: Wrong password.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mBadCredentialsException\u001b[0m                   Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[9], line 6\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[39m# carrega a lib e faz login na conta\u001b[39;00m\n\u001b[0;32m      5\u001b[0m L \u001b[39m=\u001b[39m instaloader\u001b[39m.\u001b[39mInstaloader()\n\u001b[1;32m----> 6\u001b[0m L\u001b[39m.\u001b[39;49mlogin(\u001b[39m'\u001b[39;49m\u001b[39mpulppor\u001b[39;49m\u001b[39m'\u001b[39;49m,\u001b[39m'\u001b[39;49m\u001b[39m@Monttara1\u001b[39;49m\u001b[39m'\u001b[39;49m)\n\u001b[0;32m      8\u001b[0m \u001b[39m# carrega os dados dos 'seguidores' e 'seguindo' do perfil\u001b[39;00m\n\u001b[0;32m      9\u001b[0m seguidores \u001b[39m=\u001b[39m instaloader\u001b[39m.\u001b[39mProfile\u001b[39m.\u001b[39mfrom_username(L\u001b[39m.\u001b[39mcontext,\u001b[39m\"\u001b[39m\u001b[39mpulppor\u001b[39m\u001b[39m\"\u001b[39m)\u001b[39m.\u001b[39mger_followers()\n",
      "File \u001b[1;32mc:\\Python310\\lib\\site-packages\\instaloader\\instaloader.py:634\u001b[0m, in \u001b[0;36mInstaloader.login\u001b[1;34m(self, user, passwd)\u001b[0m\n\u001b[0;32m    626\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mlogin\u001b[39m(\u001b[39mself\u001b[39m, user: \u001b[39mstr\u001b[39m, passwd: \u001b[39mstr\u001b[39m) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m \u001b[39mNone\u001b[39;00m:\n\u001b[0;32m    627\u001b[0m     \u001b[39m\"\"\"Log in to instagram with given username and password and internally store session object.\u001b[39;00m\n\u001b[0;32m    628\u001b[0m \n\u001b[0;32m    629\u001b[0m \u001b[39m    :raises InvalidArgumentException: If the provided username does not exist.\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    632\u001b[0m \u001b[39m    :raises TwoFactorAuthRequiredException: First step of 2FA login done, now call\u001b[39;00m\n\u001b[0;32m    633\u001b[0m \u001b[39m       :meth:`Instaloader.two_factor_login`.\"\"\"\u001b[39;00m\n\u001b[1;32m--> 634\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mcontext\u001b[39m.\u001b[39;49mlogin(user, passwd)\n",
      "File \u001b[1;32mc:\\Python310\\lib\\site-packages\\instaloader\\instaloadercontext.py:257\u001b[0m, in \u001b[0;36mInstaloaderContext.login\u001b[1;34m(self, user, passwd)\u001b[0m\n\u001b[0;32m    254\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m resp_json[\u001b[39m'\u001b[39m\u001b[39mauthenticated\u001b[39m\u001b[39m'\u001b[39m]:\n\u001b[0;32m    255\u001b[0m     \u001b[39mif\u001b[39;00m resp_json[\u001b[39m'\u001b[39m\u001b[39muser\u001b[39m\u001b[39m'\u001b[39m]:\n\u001b[0;32m    256\u001b[0m         \u001b[39m# '{\"authenticated\": false, \"user\": true, \"status\": \"ok\"}'\u001b[39;00m\n\u001b[1;32m--> 257\u001b[0m         \u001b[39mraise\u001b[39;00m BadCredentialsException(\u001b[39m'\u001b[39m\u001b[39mLogin error: Wrong password.\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[0;32m    258\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[0;32m    259\u001b[0m         \u001b[39m# '{\"authenticated\": false, \"user\": false, \"status\": \"ok\"}'\u001b[39;00m\n\u001b[0;32m    260\u001b[0m         \u001b[39m# Raise InvalidArgumentException rather than BadCredentialException, because BadCredentialException\u001b[39;00m\n\u001b[0;32m    261\u001b[0m         \u001b[39m# triggers re-asking of password in Instaloader.interactive_login(), which makes no sense if the\u001b[39;00m\n\u001b[0;32m    262\u001b[0m         \u001b[39m# username is invalid.\u001b[39;00m\n\u001b[0;32m    263\u001b[0m         \u001b[39mraise\u001b[39;00m InvalidArgumentException(\u001b[39m'\u001b[39m\u001b[39mLogin error: User \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m does not exist.\u001b[39m\u001b[39m'\u001b[39m\u001b[39m.\u001b[39mformat(user))\n",
      "\u001b[1;31mBadCredentialsException\u001b[0m: Login error: Wrong password."
     ]
    }
   ],
   "source": [
    "from datetime import datetime\n",
    "import instaloader\n",
    "\n",
    "# carrega a lib e faz login na conta\n",
    "L = instaloader.Instaloader()\n",
    "L.login('pulppor','@senha')\n",
    "\n",
    "# carrega os dados dos 'seguidores' e 'seguindo' do perfil\n",
    "seguidores = instaloader.Profile.from_username(L.context,\"pulppor\").ger_followers()\n",
    "seguindo = instaloader.Profile.from_username(L.context,\"pulppor\").ger_followees()\n",
    "\n",
    "print('\\nSeguidores: '+ str(seguidores._date['count']))\n",
    "print('\\nSeguindo: '+ str(seguindo._date['count']))\n",
    "print('\\n\\nLista e informações de seguidores:\\n')\n",
    "print(seguidores._data['edges'])\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.6"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
